---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devops-toolkit-stage
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/addisuyimer/devops-toolkit
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-toolkit-stage
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlays/stage 
  prune: true
  sourceRef:
    kind: GitRepository
    name: devops-toolkit
