apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: overlays-prod
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: devops-toolkit
