apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: overlays-stage
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./overlays/stage 
  prune: true
  sourceRef:
    kind: GitRepository
    name: devops-toolkit
