apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: production
commonLabels:
  env: prod
patches:
  - target:
      kind: Deployment
      name: busybox
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
resources:
- ../../base
