apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: production
commonLabels:
  env: prod
patches:
  - target:
      kind: Deployment
      name: busybox-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
