apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stage-
namespace: staging
commonLabels:
  env: stage
patches:
  - target:
      kind: Deployment
      name: busybox-deployoment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
resources:
- ../../base
